# Generated by Django 5.2.17 on 2026-10-10 12:47

import django.db.models.deletion
import domain.website.models.site_document
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('consultation_fee_currency', models.CharField(default='ZMW', max_length=3)),
                ('bank_details', models.TextField(blank=True, help_text='Shown in the payment email. Bank, account name, number, branch.')),
                ('mobile_money_details', models.TextField(blank=True, help_text='Shown in the payment email. Network, name, number.')),
                ('default_consultation_location', models.CharField(blank=True, help_text='Pre-filled when booking a consultation, e.g. the office address.', max_length=200)),
                ('contact_phone', models.CharField(blank=True, default='+260 779 127 695', max_length=30)),
                ('contact_email', models.EmailField(blank=True, default='info@elyriamatchmaking.com', max_length=254)),
                ('business_address', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='SiteDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('privacy_policy', 'Privacy Policy')], max_length=40, unique=True)),
                ('file', models.FileField(upload_to='documents/', validators=[domain.website.models.site_document.validate_pdf])),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
