# Generated by Django 5.2.17 on 2026-10-10 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_elyriapermissions_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elyriapermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': [('access_member_portal', 'Can use the member portal'), ('view_consultation_request', 'Can view consultation requests'), ('manage_consultation_request', 'Can mark fees paid, record consultations and confirm membership'), ('handle_enquiry', 'Can handle general enquiries'), ('manage_client', 'Can view and update client profiles and cross-checks'), ('manage_matching', 'Can shortlist matches and record feedback and observations'), ('manage_event', 'Can manage events'), ('manage_staff', 'Can manage staff accounts and settings'), ('view_all_consultation_requests', 'Can see every consultation request, not just assigned ones'), ('view_all_members', 'Can see every member, not just their own')]},
        ),
    ]
