# Generated by Django 5.2.17 on 2026-10-08 06:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('preferred_name', models.CharField(max_length=80)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=20)),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20, message='You must be at least 20 to apply.'), django.core.validators.MaxValueValidator(90, message='Please enter an age of 90 or under.')])),
                ('seeking', models.CharField(choices=[('man', 'A man'), ('woman', 'A woman')], max_length=20)),
                ('relationship_status', models.CharField(choices=[('single', 'Single (never married)'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('separated', 'Separated'), ('married', 'Married')], max_length=20)),
                ('location', models.CharField(max_length=150, verbose_name='Location (country / city)')),
                ('nationality', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=150, verbose_name='Occupation / profession')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('fee_paid', 'Fee paid'), ('consulted', 'Consulted'), ('became_member', 'Became member'), ('declined', 'Declined'), ('closed', 'Closed')], db_index=True, default='awaiting_payment', max_length=20)),
                ('resubmission_count', models.PositiveIntegerField(default=0, help_text='Times the same email submitted again while this request was open.')),
                ('last_resubmitted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_consultation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
