# Generated by Django 5.2.17 on 2026-10-08 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0002_consultationrequest_fee_marked_paid_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='fee_currency',
            field=models.CharField(blank=True, choices=[('ZMW', 'ZMW (Kwacha)'), ('USD', 'USD')], max_length=3),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='fee_payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Bank transfer'), ('mobile_money', 'Mobile money'), ('cash', 'Cash'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='fee_reference',
            field=models.CharField(blank=True, help_text='Bank or mobile money reference.', max_length=100),
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('held_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('conducted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_conducted', to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='matchmaking.consultationrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
