# Generated by Django 5.2.17 on 2026-10-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0003_consultationrequest_fee_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='location',
            field=models.CharField(blank=True, help_text='Where it will happen, e.g. Elyria office, video call, or an agreed venue.', max_length=200),
        ),
    ]
