# Generated by Django 5.2.17 on 2026-10-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0005_client_membership_membershippayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='relationship_status_other',
            field=models.CharField(blank=True, max_length=200, verbose_name='Relationship status (explained)'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='preferred_name',
            field=models.CharField(blank=True, help_text='Optional', max_length=80),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='relationship_status',
            field=models.CharField(choices=[('single', 'Single'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('separated', 'Separated'), ('married', 'Married'), ('other', 'Other (please explain)')], max_length=20),
        ),
    ]
