# Generated by Django 5.2.17 on 2026-10-10 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0006_consultationrequest_relationship_status_other_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text="Standard price. Leave blank if it's agreed case by case.", max_digits=10, null=True)),
                ('currency', models.CharField(choices=[('ZMW', 'ZMW (Kwacha)'), ('USD', 'USD')], default='ZMW', max_length=3)),
                ('duration_months', models.PositiveSmallIntegerField(default=12)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to retire a tier without affecting existing members.')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='membership',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='matchmaking.membershiptier'),
        ),
    ]
