# Generated by Django 5.2.17 on 2026-10-10 12:10

from django.db import migrations
TIERS = ["Bronze", "Silver", "Gold", "Elite Grade"]

def seed(apps, schema_editor):
    Tier = apps.get_model("matchmaking", "MembershipTier")
    for order, name in enumerate(TIERS, start=1):
        # Prices left blank until Elyria confirms them
        Tier.objects.get_or_create(name=name, defaults={"display_order": order, "duration_months": 12})


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0007_membershiptier_alter_membership_tier'),
    ]

    operations = [migrations.RunPython(seed, migrations.RunPython.noop)]
